### ISSUE TITLE
License

### ISSUE THREAD

**Issue by philipbjorge** [liruqi/jsonviewer#1]
Hi,
What license is your tool released under?

Thanks,
Philip

**Comment by liruqi** [comment]
@philipbjorge I grabbed the source code from http://jsonviewer.stack.hu/ 
Maybe you should ask the real author there. 
He left an email in about page.

**Comment by shadiakiki1986** [comment]
Just came across this and was wondering the same. Sent an email to the original author just now.

**Comment by Caleb-Irwin** [comment]
@shadiakiki1986 have you gotten a reply?

**Comment by shadiakiki1986** [comment]
No
